version: "3.9"
services:
  web:
    build: docker/
    restart: on-failure:5
    ports:
      - 8001:80
      - 44301:443
    volumes:
      - ./:/app/CertSign

  db:
    image: mysql
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "certsign"
    volumes:
      - ./docker/db/data:/var/lib/mysql