version: "3.9"
services:
  webserver:
    build: webserver/
    restart: on-failure:5
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"

  db:
    image: mysql
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3300:3306
    volumes:
      - ./db:/var/lib/mysql