version: "3.9"
services:
  web:
    build: docker/
    restart: on-failure:5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app/CertSign

  db:
    image: mysql
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3300:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql